import { titleIcons } from '../../src/utility/icon';

const feedData = [
  {
    id: 1,
    image: 'https://source.unsplash.com/random/50x50/?profile/1',
    nickname: '강성일',
    icon: titleIcons[0],
    level: 5,
    uploadImage: '업로드 이미지 URL 1',
    content: '글 내용 1',
    timestamp: '2023/08/27 06:02',
    likeIcon: '좋아요 아이콘 URL 1',
    likeCount: 10,
    commentIcon: '코멘트 아이콘 URL 1',
    commentCount: 5,
  },
  {
    id: 2,
    image: 'https://source.unsplash.com/random/50x50/?profile/2',
    nickname: '한도석',
    icon: titleIcons[0],
    level: 3,
    uploadImage: '업로드 이미지 URL 2',
    content: '글 내용 2',
    timestamp: '2023/08/20 14:45',
    likeIcon: '좋아요 아이콘 URL 2',
    likeCount: 15,
    commentIcon: '코멘트 아이콘 URL 2',
    commentCount: 7,
  },
  {
    id: 3,
    image: 'https://source.unsplash.com/random/50x50/?profile/3',
    nickname: '김동훈',
    icon: titleIcons[0],
    level: 2,
    uploadImage: '업로드 이미지 URL 3',
    content: '글 내용 3',
    timestamp: '2023/08/15 09:30',
    likeIcon: '좋아요 아이콘 URL 3',
    likeCount: 20,
    commentIcon: '코멘트 아이콘 URL 3',
    commentCount: 3,
  },
  {
    id: 4,
    image: 'https://source.unsplash.com/random/50x50/?profile/4',
    nickname: '이지원',
    icon: titleIcons[0],
    level: 4,
    uploadImage: '업로드 이미지 URL 4',
    content: '글 내용 4',
    timestamp: '2023/08/12 20:15',
    likeIcon: '좋아요 아이콘 URL 4',
    likeCount: 8,
    commentIcon: '코멘트 아이콘 URL 4',
    commentCount: 12,
  },
  {
    id: 5,
    image: 'https://source.unsplash.com/random/50x50/?profile/5',
    nickname: '김사덕',
    icon: titleIcons[0],
    level: 1,
    uploadImage: '업로드 이미지 URL 5',
    content: '글 내용 5',
    timestamp: '2023/08/08 11:55',
    likeIcon: '좋아요 아이콘 URL 5',
    likeCount: 25,
    commentIcon: '코멘트 아이콘 URL 5',
    commentCount: 2,
  },
  {
    id: 6,
    image: 'https://source.unsplash.com/random/50x50/?profile/6',
    nickname: '이강석',
    icon: titleIcons[0],
    level: 3,
    uploadImage: '업로드 이미지 URL 6',
    content: '글 내용 6',
    timestamp: '2023/08/04 18:20',
    likeIcon: '좋아요 아이콘 URL 6',
    likeCount: 18,
    commentIcon: '코멘트 아이콘 URL 6',
    commentCount: 9,
  },
  {
    id: 7,
    image: 'https://source.unsplash.com/random/50x50/?profile/7',
    nickname: '조연성',
    icon: titleIcons[0],
    level: 2,
    uploadImage: '업로드 이미지 URL 7',
    content: '글 내용 7',
    timestamp: '2023/07/31 03:40',
    likeIcon: '좋아요 아이콘 URL 7',
    likeCount: 14,
    commentIcon: '코멘트 아이콘 URL 7',
    commentCount: 6,
  },
  {
    id: 8,
    image: 'https://source.unsplash.com/random/50x50/?profile/8',
    nickname: 'FE_멘토님',
    icon: titleIcons[0],
    level: 99,
    uploadImage: '업로드 이미지 URL 8',
    content: '글 내용 8',
    timestamp: '2023/07/25 22:12',
    likeIcon: '좋아요 아이콘 URL 8',
    likeCount: 11,
    commentIcon: '코멘트 아이콘 URL 8',
    commentCount: 3,
  },
  {
    id: 9,
    image: 'https://source.unsplash.com/random/50x50/?profile/9',
    nickname: 'BE_멘토님',
    icon: titleIcons[0],
    level: 99,
    uploadImage: '업로드 이미지 URL 9',
    content: '글 내용 9',
    timestamp: '2023/07/19 07:28',
    likeIcon: '좋아요 아이콘 URL 9',
    likeCount: 22,
    commentIcon: '코멘트 아이콘 URL 9',
    commentCount: 10,
  },
];

export default feedData;
